#!/usr/bin/env python3

# -*- coding: utf-8 -*- 

# from collections import named tuple module.
from collections import namedtuple
# import random module
import random
# import regex module
import re
# import system module
import sys

########################
### File information ###
########################

__author__  = "Lindsay Gelle (https://github.com/gellel)"

__version__ = "1.0"

__all__ = [
	"BULBASAUR",
	"IVYSAUR",
	"VENUSAUR",
	"CHARMANDER",
	"CHARMELEON",
	"CHARIZARD",
	"SQUIRTLE",
	"WARTORTLE",
	"BLASTOISE",
	"CATERPIE",
	"METAPOD",
	"BUTTERFREE",
	"WEEDLE",
	"KAKUNA",
	"BEEDRILL",
	"PIDGEY",
	"PIDGEOTTO",
	"PIDGEOT",
	"RATTATA",
	"RATICATE",
	"SPEAROW",
	"FEAROW",
	"EKANS",
	"ARBOK",
	"PIKACHU",
	"RAICHU",
	"SANDSHREW",
	"SANDSLASH",
	"NIDORAN_MALE",
	"NIDORINA",
	"NIDOQUEEN",
	"NIDORAN_FEMALE",
	"NIDORINO",
	"NIDOKING",
	"CLEFAIRY",
	"CLEFABLE",
	"VULPIX",
	"NINETALES",
	"JIGGLYPUFF",
	"WIGGLYTUFF",
	"ZUBAT",
	"GOLBAT",
	"ODDISH",
	"GLOOM",
	"VILEPLUME",
	"PARAS",
	"PARASECT",
	"VENONAT",
	"VENOMOTH",
	"DIGLETT",
	"DUGTRIO",
	"MEOWTH",
	"PERSIAN",
	"PSYDUCK",
	"GOLDUCK",
	"MANKEY",
	"PRIMEAPE",
	"GROWLITHE",
	"ARCANINE",
	"POLIWAG",
	"POLIWHIRL",
	"POLIWRATH",
	"ABRA",
	"KADABRA",
	"ALAKAZAM",
	"MACHOP",
	"MACHOKE",
	"MACHAMP",
	"BELLSPROUT",
	"WEEPINBELL",
	"VICTREEBEL",
	"TENTACOOL",
	"TENTACRUEL",
	"GEODUDE",
	"GRAVELER",
	"GOLEM",
	"PONYTA",
	"RAPIDASH",
	"SLOWPOKE",
	"SLOWBRO",
	"MAGNEMITE",
	"MAGNETON",
	"FARFETCHD",
	"DODUO",
	"DODRIO",
	"SEEL",
	"DEWGONG",
	"GRIMER",
	"MUK",
	"SHELLDER",
	"CLOYSTER",
	"GASTLY",
	"HAUNTER",
	"GENGAR",
	"ONIX",
	"DROWZEE",
	"HYPNO",
	"KRABBY",
	"KINGLER",
	"VOLTORB",
	"ELECTRODE",
	"EXEGGCUTE",
	"EXEGGUTOR",
	"CUBONE",
	"MAROWAK",
	"HITMONLEE",
	"HITMONCHAN",
	"LICKITUNG",
	"KOFFING",
	"WEEZING",
	"RHYHORN",
	"RHYDON",
	"CHANSEY",
	"TANGELA",
	"KANGASKHAN",
	"HORSEA",
	"SEADRA",
	"GOLDEEN",
	"SEAKING",
	"STARYU",
	"STARMIE",
	"MR_MIME",
	"SCYTHER",
	"JYNX",
	"ELECTABUZZ",
	"MAGMAR",
	"PINSIR",
	"TAUROS",
	"MAGIKARP",
	"GYARADOS",
	"LAPRAS",
	"DITTO",
	"EEVEE",
	"VAPOREON",
	"JOLTEON",
	"FLAREON",
	"PORYGON",
	"OMANYTE",
	"OMASTAR",
	"KABUTO",
	"KABUTOPS",
	"AERODACTYL",
	"SNORLAX",
	"ARTICUNO",
	"ZAPDOS",
	"MOLTRES",
	"DRATINI",
	"DRAGONAIR",
	"DRAGONITE",
	"MEWTWO",
	"MEW"]

########################
### Module constants ###
########################

BULBASAUR = dict(
	POKEDEX = 1,
	EN_NAME = "BULBASAUR",
	JP_NAME = "FUSHIGIDANE",
	SPECIES = "SEED",
	TYPES = (
		("GRASS", 1), 
		("POISON", 2)),
	ABILITIES = (
		("GROWL", 1),
		("GROWTH", 34),
		("LEECH_SEED", 7),
		("POISON_POWDER", 20),
		("RAZOR_LEAF", 27),
		("SLEEP_POWDER", 41),
		("SOLAR_BEAM", 48),
		("TACKLE", 1),
		("VINE_WHIP", 13)),
	TRAINING = (
		("EV_YIELD", 1, "SPECIAL_ATTACK"),
		("CATCH_RATE", 45, 5.9, "POKEBALL"),
		("BASE_HAPPINESS", 70, "NORMAL"),
		("BASE_EXP", 64),
		("GROWTH_RATE", "MEDIUM_SLOW")),
	BREEDING = (
		("GROUPS", (("GRASS", 1), ("MONSTER", 2))),
		("GENDER", (("MALE", 87.5), ("FEMALE", 12.5))),
		("EGG_CYCLES", 20, 5120)),
	STATS = (
		("HP", 45, 200, 294),
		("ATTACK", 49, 92, 216),
		("DEFENSE", 49, 92, 216),
		("SP_ATTACK", 65, 121, 251),
		("SP_DEFENSE", 65, 121, 251),
		("SPEED", 45, 85, 207)),
	EVOLUTION = (
		("IVYSAUR", 2, 16),
		("VENUSAUR", 3, 32)))
