#!/usr/bin/env python3
# -*- coding: utf-8 -*- 

###########################
### Required ##############
###########################

import sys

import os

###########################
### Paths #################
###########################

os.chdir(os.path.realpath(os.path.dirname(sys.argv[0])))

sys.path.append("../../../lib/constructors/moveset/")

###########################
### Supports ##############
###########################

from moveset import Move

###########################
### About #################
###########################

__author__ = "Lindsay Gelle (gellel)"

###########################
### Exports ###############
###########################

__all__ = [
	"ABSORB",
	"ACID",
	"ACID_ARMOUR",
	"AGILITY",
	"AMNESIA",
	"AURORA_BEAM",
	"BARRAGE",
	"BARRIER",
	"BIDE",
	"BIND",
	"BITE",
	"BLIZZARD",
	"BODY_SLAM",
	"BONEMERANG",
	"BONE_CLUB",
	"BUBBLE",
	"BUBBLE_BEAM",
	"CLAMP",
	"COMET_PUNCH",
	"CONFUSE_RAY",
	"CONFUSION",
	"CONSTRICT",
	"CONVERSION",
	"COUNTER",
	"CRABHAMMER",
	"CUT",
	"DEFENSE_CURL",
	"DIG",
	"DISABLE",
	"DIZZY_PUNCH",
	"DOUBLE_EDGE",
	"DOUBLE_KICK",
	"DOUBLE_SLAP",
	"DOUBLE_TEAM",
	"DRAGON_RAGE",
	"DREAM_EATER",
	"DRILL_PECK",
	"EARTHQUAKE",
	"EGG_BOMB",
	"EMBER",
	"EXPLOSION",
	"FIRE_BLAST",
	"FIRE_PUNCH",
	"FIRE_SPIN",
	"FISSURE",
	"FLAMETHROWER",
	"FLASH",
	"FLY",
	"FOCUS_ENERGY",
	"FURY_ATTACK",
	"FURY_SWIPES",
	"GLARE",
	"GROWL",
	"GROWTH",
	"GUILLOTINE",
	"GUST",
	"HARDEN",
	"HAZE",
	"HEADBUTT",
	"HORN_ATTACK",
	"HORN_DRILL",
	"HYDRO_PUMP",
	"HYPER_BEAM",
	"HYPER_FANG",
	"HYPNOSIS",
	"ICE_BEAM",
	"ICE_PUNCH",
	"JUMP_KICK",
	"KARATE_CHOP",
	"KINESIS",
	"LEECH_LIFE",
	"LEECH_SEED",
	"LEER",
	"LICK",
	"LIGHT_SCREEN",
	"LOVELY_KISS",
	"LOW_KICK",
	"MEDITATE",
	"MEGA_DRAIN",
	"MEGA_KICK",
	"MEGA_PUNCH",
	"METRONOME",
	"MIMIC",
	"MINIMIZE",
	"MIRROR_MOVE",
	"MIST",
	"NIGHT_SHADE",
	"PAY_DAY",
	"PECK",
	"PETAL_DANCE",
	"PIN_MISSILE",
	"POISON_GAS",
	"POISON_POWDER",
	"POISON_STING",
	"POUND",
	"PSYBEAM",
	"PSYCHIC",
	"PSYWAVE",
	"QUICK_ATTACK",
	"RAGE",
	"RAZOR_LEAF",
	"RAZOR_WIND",
	"RECOVER",
	"REFLECT",
	"REST",
	"ROAR",
	"ROCK_SLIDE",
	"ROCK_THROW",
	"ROLLING_KICK",
	"SAND_ATTACK",
	"SCRATCH",
	"SCREECH",
	"SEISMIC_TOSS",
	"SELF_DESTRUCT",
	"SHARPEN",
	"SING",
	"SKULL_BASH",
	"SKY_ATTACK",
	"SLAM",
	"SLASH",
	"SLEEP_POWDER",
	"SLUDGE",
	"SMOG",
	"SMOKESCREEN",
	"SOFT_BOILED",
	"SOLAR_BEAM",
	"SONIC_BOOM",
	"SPIKE_CANNON",
	"SPLASH",
	"SPORE",
	"STOMP",
	"STRENGTH",
	"STRING_SHOT",
	"STRUGGLE",
	"STUN_SPORE",
	"SUBMISSION",
	"SUBSTITUTE",
	"SUPERSONIC",
	"SUPER_FANG",
	"SURF",
	"SWIFT",
	"SWORDS_DANCE",
	"TACKLE",
	"TAIL_WHIP",
	"TAKE_DOWN",
	"TELEPORT",
	"THRASH",
	"THUNDER",
	"THUNDERBOLT",
	"THUNDER_PUNCH",
	"THUNDER_SHOCK",
	"THUNDER_WAVE",
	"TOXIC",
	"TRANSFORM",
	"TRI_ATTACK",
	"TWINEEDLE",
	"VICE_GRIP",
	"VINE_WHIP",
	"WATERFALL",
	"WATER_GUN",
	"WHIRLWIND",
	"WING_ATTACK",
	"WITHDRAW"]

###########################
### Constants #############
###########################

ABSORB = Move(
	ELEMENT_TYPE = "GRASS",
	CATEGORY = "SPECIAL",
	POWER = 20,
	ACCURACY = 100,
	POWER_POINTS = 25,
	DESCRIPTION = "USER RECOVERS HALF THE HP INFLICTED ON OPPONENT.")

ACID = Move(
	ELEMENT_TYPE = "POISON",
	CATEGORY = "SPECIAL",
	POWER = 40,
	ACCURACY = 100,
	POWER_POINTS = 30,
	DESCRIPTION = "MAY LOWER OPPONENT'S SPECIAL DEFENSE.")

ACID_ARMOUR = Move(
	ELEMENT_TYPE = "POISON",
	CATEGORY = "STATUS",
	POWER = None, 
	ACCURACY = None,
	POWER_POINTS = 20,
	DESCRIPTION = "SHARPLY RAISES USER'S DEFENSE.")

AGILITY = Move(
	ELEMENT_TYPE = "PSYCHIC",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 30,
	DESCRIPTION = "SHARPLY RAISES USER'S SPEED.")

AMNESIA = Move(
	ELEMENT_TYPE = "PSYCHIC",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 20,
	DESCRIPTION = "SHARPLY RAISES USER'S SPECIAL DEFENSE.")

AURORA_BEAM = Move(
	ELEMENT_TYPE = "ICE",
	CATEGORY = "SPECIAL",
	POWER = 65, 
	ACCURACY = 100,
	POWER_POINTS = 20,
	DESCRIPTION = "MAY LOWER OPPONENT'S ATTACK.")

BARRAGE = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 15,
	ACCURACY = 85,
	POWER_POINTS = 20,
	DESCRIPTION = "HITS 2-5 TIMES IN ONE TURN.")

BARRIER = Move(
 	ELEMENT_TYPE = "PSYCHIC",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 20,
	DESCRIPTION = "SHARPLY RAISES USER'S DEFENSE.")

BIDE = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 10,
	DESCRIPTION = "USER TAKES DAMAGE FOR TWO TURNS THEN STRIKES BACK DOUBLE.")

BIND = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 15,
	ACCURACY = 85,
	POWER_POINTS = 20,
	DESCRIPTION = "TRAPS OPPONENT, DAMAGING THEM FOR 4-5 TURNS.")

BITE = Move(
 	ELEMENT_TYPE = "DARK",
	CATEGORY = "PHYSICAL",
	POWER = 60,
	ACCURACY = 100,
	POWER_POINTS = 25,
	DESCRIPTION = "MAY CAUSE FLINCHING.")

BLIZZARD = Move(
 	ELEMENT_TYPE = "ICE",
	CATEGORY = "SPECIAL",
	POWER = 110,
	ACCURACY = 70,
	POWER_POINTS = 5,
	DESCRIPTION = "MAY FREEZE OPPONENT.")

BODY_SLAM = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 85,
	ACCURACY = 100,
	POWER_POINTS = 15,
	DESCRIPTION = "MAY PARALYZE OPPONENT.")

BONE_CLUB = Move(
	ELEMENT_TYPE = "GROUND",
	CATEGORY = "PHYSICAL",
	POWER = 65,
	ACCURACY = 85,
	POWER_POINTS = 20,
	DESCRIPTION = "MAY CAUSE FLINCHING.")

BONEMERANG = Move(
 	ELEMENT_TYPE = "GROUND",
	CATEGORY = "PHYSICAL",
	POWER = 50,
	ACCURACY = 90,
	POWER_POINTS = 10,
	DESCRIPTION = "HITS TWICE IN ONE TURN.")

BUBBLE = Move(
 	ELEMENT_TYPE = "WATER",
	CATEGORY = "SPECIAL",
	POWER = 40,
	ACCURACY = 100,
	POWER_POINTS = 30,
	DESCRIPTION = "MAY LOWER OPPONENT'S SPEED.")

BUBBLE_BEAM = Move(
	ELEMENT_TYPE = "WATER",
	CATEGORY = "SPECIAL",
	POWER = 65, 
	ACCURACY = 100,
	POWER_POINTS = 20,
	DESCRIPTION = "MAY LOWER OPPONENT'S SPEED.")

CLAMP = Move(
 	ELEMENT_TYPE = "WATER",
	CATEGORY = "PHYSICAL",
	POWER = 35,
	ACCURACY = 85,
	POWER_POINTS = 10,
	DESCRIPTION = "TRAPS OPPONENT, DAMAGING THEM FOR 4-5 TURNS.")

COMET_PUNCH = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 18,
	ACCURACY = 85,
	POWER_POINTS = 15,
	DESCRIPTION = "HITS 2-5 TIMES IN ONE TURN.")

CONFUSE_RAY = Move(
	ELEMENT_TYPE = "GHOST",
	CATEGORY = "STATUS",
	POWER = None, 
	ACCURACY = 100,
	POWER_POINTS = 10,
	DESCRIPTION = "CONFUSES OPPONENT.")

CONFUSION = Move(
 	ELEMENT_TYPE = "PSYCHIC",
	CATEGORY = "SPECIAL",
	POWER = 50,
	ACCURACY = 100,
	POWER_POINTS = 25,
	DESCRIPTION = "MAY CONFUSE OPPONENT.")

CONSTRICT = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 10,
	ACCURACY = 100,
	POWER_POINTS = 35,
	DESCRIPTION = "MAY LOWER OPPONENT'S SPEED BY ONE STAGE.")

CONVERSION = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 30,
	DESCRIPTION = "CHANGES USER'S TYPE TO THAT OF ITS FIRST MOVE.")

COUNTER = Move(
 	ELEMENT_TYPE = "FIGHTING",
	CATEGORY = "PHYSICAL",
	POWER = None,
	ACCURACY = 100,
	POWER_POINTS = 20,
	DESCRIPTION = "WHEN HIT BY A PHYSICAL ATTACK, USER STRIKES BACK WITH 2X POWER.")

CRABHAMMER = Move(
 	ELEMENT_TYPE = "WATER",
	CATEGORY = "PHYSICAL",
	POWER = 100,
	ACCURACY = 90,
	POWER_POINTS = 10,
	DESCRIPTION = "HIGH CRITICAL HIT RATIO.")

CUT = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 50,
	ACCURACY = 95,
	POWER_POINTS = 30,
	DESCRIPTION = None)

DEFENSE_CURL = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None, 
	ACCURACY = None,
	POWER_POINTS = 40,
	DESCRIPTION = "RAISES USER'S DEFENSE.")

DIG = Move(
 	ELEMENT_TYPE = "GROUND",
	CATEGORY = "PHYSICAL",
	POWER = 80,
	ACCURACY = 100,
	POWER_POINTS = 10,
	DESCRIPTION = "DIGS UNDERGROUND ON FIRST TURN, ATTACKS ON SECOND. CAN ALSO ESCAPE FROM CAVES.")

DISABLE = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = 100,
	POWER_POINTS = 20,
	DESCRIPTION = "OPPONENT CAN'T USE ITS LAST ATTACK FOR A FEW TURNS.")

DIZZY_PUNCH = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 70,
	ACCURACY = 100,
	POWER_POINTS = 10,
	DESCRIPTION = "MAY CONFUSE OPPONENT.")

DOUBLE_KICK = Move(
	ELEMENT_TYPE = "FIGHTING",
	CATEGORY = "PHYSICAL",
	POWER = 30,
	ACCURACY = 100,
	POWER_POINTS = 30,
	DESCRIPTION = "HITS TWICE IN ONE TURN.")

DOUBLE_SLAP = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 15,
	ACCURACY = 85,
	POWER_POINTS = 10,
	DESCRIPTION = "HITS 2-5 TIMES IN ONE TURN.")

DOUBLE_TEAM = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None, 
	ACCURACY = None,
	POWER_POINTS = 15,
	DESCRIPTION = "RAISES USER'S EVASIVENESS.")

DOUBLE_EDGE = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 120, 
	ACCURACY = 100,
	POWER_POINTS = 15,
	DESCRIPTION = "USER RECEIVES RECOIL DAMAGE.")

DRAGON_RAGE = Move(
	ELEMENT_TYPE = "DRAGON",
	CATEGORY = "SPECIAL",
	POWER = None,
	ACCURACY = 100,
	POWER_POINTS = 10,
	DESCRIPTION = "ALWAYS INFLICTS 40 HP.")

DREAM_EATER = Move(
	ELEMENT_TYPE = "PSYCHIC",
	CATEGORY = "SPECIAL",
	POWER = 100,
	ACCURACY = 100,
	POWER_POINTS = 15,
	DESCRIPTION = "USER RECOVERS HALF THE HP INFLICTED ON A SLEEPING OPPONENT.")

DRILL_PECK = Move(
	ELEMENT_TYPE = "FLYING",
	CATEGORY = "PHYSICAL",
	POWER = 80,
	ACCURACY = 100,
	POWER_POINTS = 20,
	DESCRIPTION = None)

EARTHQUAKE = Move(
 	ELEMENT_TYPE = "GROUND",
	CATEGORY = "PHYSICAL",
	POWER = 100,
	ACCURACY = 100,
	POWER_POINTS = 10,
	DESCRIPTION = "POWER IS DOUBLED IF OPPONENT IS UNDERGROUND FROM USING DIG.")

EGG_BOMB = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 100, 
	ACCURACY = 75,
	POWER_POINTS = 10,
	DESCRIPTION = None)

EMBER = Move(
 	ELEMENT_TYPE = "FIRE",
	CATEGORY = "SPECIAL",
	POWER = 40,
	ACCURACY = 100,
	POWER_POINTS = 25,
	DESCRIPTION = "MAY BURN OPPONENT.")

EXPLOSION = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 250,
	ACCURACY = 100,
	POWER_POINTS = 5,
	DESCRIPTION = "USER FAINTS.")

FIRE_BLAST = Move(
	ELEMENT_TYPE = "FIRE",
	CATEGORY = "SPECIAL",
	POWER = 110, 
	ACCURACY = 85,
	POWER_POINTS = 5,
	DESCRIPTION = "MAY BURN OPPONENT.")

FIRE_PUNCH = Move(
	ELEMENT_TYPE = "FIRE",
	CATEGORY = "PHYSICAL",
	POWER = 75,
	ACCURACY = 100,
	POWER_POINTS = 15,
	DESCRIPTION = "MAY BURN OPPONENT.")

FIRE_SPIN = Move(
	ELEMENT_TYPE = "FIRE",
	CATEGORY = "SPECIAL",
	POWER = 35, 
	ACCURACY = 85,
	POWER_POINTS = 15,
	DESCRIPTION = "TRAPS OPPONENT, DAMAGING THEM FOR 4-5 TURNS.")

FISSURE = Move(
 	ELEMENT_TYPE = "GROUND",
	CATEGORY = "PHYSICAL",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 5,
	DESCRIPTION = "ONE-HIT-KO, IF IT HITS.")

FLAMETHROWER = Move(
 	ELEMENT_TYPE = "FIRE",
	CATEGORY = "SPECIAL",
	POWER = 90,
	ACCURACY = 100,
	POWER_POINTS = 15,
	DESCRIPTION = "MAY BURN OPPONENT.")

FLASH = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = 100,
	POWER_POINTS = 20,
	DESCRIPTION = "LOWERS OPPONENT'S ACCURACY.")

FLY = Move(
 	ELEMENT_TYPE = "FLYING",
	CATEGORY = "PHYSICAL",
	POWER = 90,
	ACCURACY = 95,
	POWER_POINTS = 15,
	DESCRIPTION = "FLIES UP ON FIRST TURN, ATTACKS ON SECOND TURN.")

FOCUS_ENERGY = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None, 
	ACCURACY = None,
	POWER_POINTS = 30,
	DESCRIPTION = "INCREASES CRITICAL HIT RATIO.")

FURY_ATTACK = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 15,
	ACCURACY = 85,
	POWER_POINTS = 20,
	DESCRIPTION = "HITS 2-5 TIMES IN ONE TURN.")

FURY_SWIPES = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 18,
	ACCURACY = 80,
	POWER_POINTS = 15,
	DESCRIPTION = "HITS 2-5 TIMES IN ONE TURN.")

GLARE = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = 100,
	POWER_POINTS = 30,
	DESCRIPTION = "PARALYZES OPPONENT.")

GROWL = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = 100,
	POWER_POINTS = 40,
	DESCRIPTION = "LOWERS OPPONENT'S ATTACK.")

GROWTH = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 40,
	DESCRIPTION = "RAISES USER'S ATTACK AND SPECIAL ATTACK.")

GUILLOTINE = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 5,
	DESCRIPTION = "ONE-HIT-KO, IF IT HITS.")

GUST = Move(
 	ELEMENT_TYPE = "FLYING",
	CATEGORY = "SPECIAL",
	POWER = 40,
	ACCURACY = 100,
	POWER_POINTS = 35,
	DESCRIPTION = "HITS POKEMON USING FLY/BOUNCE WITH DOUBLE POWER.")

HARDEN = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 30,
	DESCRIPTION = "RAISES USER'S DEFENSE.")

HAZE = Move(
 	ELEMENT_TYPE = "ICE",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 30,
	DESCRIPTION = "RESETS ALL STAT CHANGES.")

HEADBUTT = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 70,
	ACCURACY = 100,
	POWER_POINTS = 15,
	DESCRIPTION = "MAY CAUSE FLINCHING.")

HIGH_JUMP_KICK = Move(
	ELEMENT_TYPE = "FIGHTING",
	CATEGORY = "PHYSICAL",
	POWER = 130, 
	ACCURACY = 90,
	POWER_POINTS = 10,
	DESCRIPTION = "IF IT MISSES, THE USER LOSES HALF THEIR HP.")

HORN_ATTACK = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 65,
	ACCURACY = 100,
	POWER_POINTS = 25,
	DESCRIPTION = None)

HORN_DRILL = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 5,
	DESCRIPTION = "ONE-HIT-KO, IF IT HITS.")

HYDRO_PUMP = Move(
	ELEMENT_TYPE = "WATER",
	CATEGORY = "SPECIAL",
	POWER = 110, 
	ACCURACY = 80,
	POWER_POINTS = 5,
	DESCRIPTION = None)

HYPER_BEAM = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "SPECIAL",
	POWER = 150, 
	ACCURACY = 90,
	POWER_POINTS = 5,
	DESCRIPTION = "USER MUST RECHARGE NEXT TURN.")

HYPER_FANG = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 80,
	ACCURACY = 90,
	POWER_POINTS = 15,
	DESCRIPTION = "MAY CAUSE FLINCHING.")

HYPNOSIS = Move(
 	ELEMENT_TYPE = "PSYCHIC",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = 60,
	POWER_POINTS = 20,
	DESCRIPTION = "PUTS OPPONENT TO SLEEP.")

ICE_BEAM = Move(
	ELEMENT_TYPE = "ICE",
	CATEGORY = "SPECIAL",
	POWER = 90, 
	ACCURACY = 100,
	POWER_POINTS = 10,
	DESCRIPTION = "MAY FREEZE OPPONENT.")

ICE_PUNCH = Move(
	ELEMENT_TYPE = "ICE",
	CATEGORY = "PHYSICAL",
	POWER = 75,
	ACCURACY = 100,
	POWER_POINTS = 15,
	DESCRIPTION = "MAY FREEZE OPPONENT.")

JUMP_KICK = Move(
	ELEMENT_TYPE = "FIGHTING",
	CATEGORY = "PHYSICAL",
	POWER = 100, 
	ACCURACY = 95,
	POWER_POINTS = 10,
	DESCRIPTION = "IF IT MISSES, THE USER LOSES HALF THEIR HP.")

KARATE_CHOP = Move(
	ELEMENT_TYPE = "FIGHTING",
	CATEGORY = "PHYSICAL",
	POWER = 50,
	ACCURACY = 100,
	POWER_POINTS = 25,
	DESCRIPTION = "HIGH CRITICAL HIT RATIO.")

KINESIS = Move(
 	ELEMENT_TYPE = "PSYCHIC",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = 80,
	POWER_POINTS = 15,
	DESCRIPTION = "LOWERS OPPONENT'S ACCURACY.")

LEECH_LIFE = Move(
	ELEMENT_TYPE = "BUG",
	CATEGORY = "PHYSICAL",
	POWER = 80,
	ACCURACY = 100,
	POWER_POINTS = 10,
	DESCRIPTION = "USER RECOVERS HALF THE HP INFLICTED ON OPPONENT.")

LEECH_SEED = Move(
	ELEMENT_TYPE = "GRASS",
	CATEGORY = "STATUS",
	POWER = None, 
	ACCURACY = 90,
	POWER_POINTS = 10,
	DESCRIPTION = "USER STEALS HP FROM OPPONENT EACH TURN.")

LEER = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = 100,
	POWER_POINTS = 30,
	DESCRIPTION = "LOWERS OPPONENT'S DEFENSE.")

LICK = Move(
 	ELEMENT_TYPE = "GHOST",
	CATEGORY = "PHYSICAL",
	POWER = 30,
	ACCURACY = 100,
	POWER_POINTS = 30,
	DESCRIPTION = "MAY PARALYZE OPPONENT.")

LIGHT_SCREEN = Move(
	ELEMENT_TYPE = "PSYCHIC",
	CATEGORY = "STATUS",
	POWER = None, 
	ACCURACY = None,
	POWER_POINTS = 30,
	DESCRIPTION = "HALVES DAMAGE FROM SPECIAL ATTACKS FOR 5 TURNS.")

LOVELY_KISS = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None, 
	ACCURACY = 75,
	POWER_POINTS = 10,
	DESCRIPTION = "PUTS OPPONENT TO SLEEP.")

LOW_KICK = Move(
	ELEMENT_TYPE = "FIGHTING",
	CATEGORY = "PHYSICAL",
	POWER = None,
	ACCURACY = 100,
	POWER_POINTS = 20,
	DESCRIPTION = "THE HEAVIER THE OPPONENT, THE STRONGER THE ATTACK.")

MEDITATE = Move(
 	ELEMENT_TYPE = "PSYCHIC",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 40,
	DESCRIPTION = "RAISES USER'S ATTACK.")

MEGA_DRAIN = Move(
	ELEMENT_TYPE = "GRASS",
	CATEGORY = "SPECIAL",
	POWER = 40, 
	ACCURACY = 100,
	POWER_POINTS = 15,
	DESCRIPTION = "USER RECOVERS HALF THE HP INFLICTED ON OPPONENT.")

MEGA_KICK = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 120, 
	ACCURACY = 75,
	POWER_POINTS = 5,
	DESCRIPTION = None)

MEGA_PUNCH = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 80,
	ACCURACY = 85,
	POWER_POINTS = 20,
	DESCRIPTION = None)

METRONOME = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 10,
	DESCRIPTION = "USER PERFORMS ANY MOVE IN THE GAME AT RANDOM.")

MIMIC = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 10,
	DESCRIPTION = "COPIES THE OPPONENT'S LAST MOVE.")

MINIMIZE = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 10,
	DESCRIPTION = "SHARPLY RAISES USER'S EVASIVENESS.")

MIRROR_MOVE = Move(
	ELEMENT_TYPE = "FLYING",
	CATEGORY = "STATUS",
	POWER = None, 
	ACCURACY = None,
	POWER_POINTS = 20,
	DESCRIPTION = "USER PERFORMS THE OPPONENT'S LAST MOVE.")

MIST = Move(
 	ELEMENT_TYPE = "ICE",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 30,
	DESCRIPTION = "USER'S STATS CANNOT BE CHANGED FOR A PERIOD OF TIME.")

NIGHT_SHADE = Move(
	ELEMENT_TYPE = "GHOST",
	CATEGORY = "SPECIAL",
	POWER = None,
	ACCURACY = 100,
	POWER_POINTS = 15,
	DESCRIPTION = "INFLICTS DAMAGE EQUAL TO USER'S LEVEL.")

PAY_DAY = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 40,
	ACCURACY = 100,
	POWER_POINTS = 20,
	DESCRIPTION = "A SMALL AMOUNT OF MONEY IS GAINED AFTER THE BATTLE RESOLVES.")

PECK = Move(
 	ELEMENT_TYPE = "FLYING",
	CATEGORY = "PHYSICAL",
	POWER = 35,
	ACCURACY = 100,
	POWER_POINTS = 35,
	DESCRIPTION = None)

PETAL_DANCE = Move(
	ELEMENT_TYPE = "GRASS",
	CATEGORY = "SPECIAL",
	POWER = 120, 
	ACCURACY = 100,
	POWER_POINTS = 10,
	DESCRIPTION = "USER ATTACKS FOR 2-3 TURNS BUT THEN BECOMES CONFUSED.")

PIN_MISSILE = Move(
	ELEMENT_TYPE = "BUG",
	CATEGORY = "PHYSICAL",
	POWER = 25,
	ACCURACY = 95,
	POWER_POINTS = 20,
	DESCRIPTION = "HITS 2-5 TIMES IN ONE TURN.")

POISON_GAS = Move(
	ELEMENT_TYPE = "POISON",
	CATEGORY = "STATUS",
	POWER = None, 
	ACCURACY = 90,
	POWER_POINTS = 40,
	DESCRIPTION = "POISONS OPPONENT.")

POISON_POWDER = Move(
	ELEMENT_TYPE = "POISON",
	CATEGORY = "STATUS",
	POWER = None, 
	ACCURACY = 75,
	POWER_POINTS = 35,
	DESCRIPTION = "POISONS OPPONENT.")

POISON_STING = Move(
	ELEMENT_TYPE = "POISON",
	CATEGORY = "PHYSICAL",
	POWER = 15,
	ACCURACY = 100,
	POWER_POINTS = 35,
	DESCRIPTION = "MAY POISON THE OPPONENT.")

POUND = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 40,
	ACCURACY = 100,
	POWER_POINTS = 35,
	DESCRIPTION = None)

PSYBEAM = Move(
 	ELEMENT_TYPE = "PSYCHIC",
	CATEGORY = "SPECIAL",
	POWER = 65,
	ACCURACY = 100,
	POWER_POINTS = 20,
	DESCRIPTION = "MAY CONFUSE OPPONENT.")

PSYCHIC = Move(
 	ELEMENT_TYPE = "PSYCHIC",
	CATEGORY = "SPECIAL",
	POWER = 90,
	ACCURACY = 100,
	POWER_POINTS = 10,
	DESCRIPTION = "MAY LOWER OPPONENT'S SPECIAL DEFENSE.")

PSYWAVE = Move(
 	ELEMENT_TYPE = "PSYCHIC",
	CATEGORY = "SPECIAL",
	POWER = None,
	ACCURACY = 80,
	POWER_POINTS = 15,
	DESCRIPTION = "INFLICTS DAMAGE 50-150% OF USER'S LEVEL.")

QUICK_ATTACK = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 40,
	ACCURACY = 100,
	POWER_POINTS = 30,
	DESCRIPTION = "USER ATTACKS FIRST.")

RAGE = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 20,
	ACCURACY = 100,
	POWER_POINTS = 20,
	DESCRIPTION = "RAISES USER'S ATTACK WHEN HIT.")

RAZOR_LEAF = Move(
	ELEMENT_TYPE = "GRASS",
	CATEGORY = "PHYSICAL",
	POWER = 55,
	ACCURACY = 95,
	POWER_POINTS = 25,
	DESCRIPTION = "HIGH CRITICAL HIT RATIO.")

RAZOR_WIND = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "SPECIAL",
	POWER = 80, 
	ACCURACY = 100,
	POWER_POINTS = 10,
	DESCRIPTION = "CHARGES ON FIRST TURN, ATTACKS ON SECOND. HIGH CRITICAL HIT RATIO.")

RECOVER = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 10,
	DESCRIPTION = "USER RECOVERS HALF ITS MAX HP.")

REFLECT = Move(
 	ELEMENT_TYPE = "PSYCHIC",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 20,
	DESCRIPTION = "HALVES DAMAGE FROM PHYSICAL ATTACKS FOR 5 TURNS.")

REST = Move(
 	ELEMENT_TYPE = "PSYCHIC",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 10,
	DESCRIPTION = "USER SLEEPS FOR 2 TURNS, BUT USER IS FULLY HEALED.")

ROAR = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 20,
	DESCRIPTION = "IN BATTLES, THE OPPONENT SWITCHES. IN THE WILD, THE POKEMON RUNS.")

ROCK_SLIDE = Move(
	ELEMENT_TYPE = "ROCK",
	CATEGORY = "PHYSICAL",
	POWER = 75,
	ACCURACY = 90,
	POWER_POINTS = 10,
	DESCRIPTION = "MAY CAUSE FLINCHING.")

ROCK_THROW = Move(
	ELEMENT_TYPE = "ROCK",
	CATEGORY = "PHYSICAL",
	POWER = 50,
	ACCURACY = 90,
	POWER_POINTS = 15,
	DESCRIPTION = None)

ROLLING_KICK = Move(
	ELEMENT_TYPE = "FIGHTING",
	CATEGORY = "PHYSICAL",
	POWER = 60,
	ACCURACY = 85,
	POWER_POINTS = 15,
	DESCRIPTION = "MAY CAUSE FLINCHING.")

SAND_ATTACK = Move(
	ELEMENT_TYPE = "GROUND",
	CATEGORY = "STATUS",
	POWER = None, 
	ACCURACY = 100,
	POWER_POINTS = 15,
	DESCRIPTION = "LOWERS OPPONENT'S ACCURACY.")

SCRATCH = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 40,
	ACCURACY = 100,
	POWER_POINTS = 35,
	DESCRIPTION = None)

SCREECH = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = 85,
	POWER_POINTS = 40,
	DESCRIPTION = "SHARPLY LOWERS OPPONENT'S DEFENSE.")

SEISMIC_TOSS = Move(
	ELEMENT_TYPE = "FIGHTING",
	CATEGORY = "PHYSICAL",
	POWER = None,
	ACCURACY = 100,
	POWER_POINTS = 20,
	DESCRIPTION = "INFLICTS DAMAGE EQUAL TO USER'S LEVEL.")

SELF_DESTRUCT = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 200, 
	ACCURACY = 100,
	POWER_POINTS = 5,
	DESCRIPTION = "USER FAINTS.")

SHARPEN = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 30,
	DESCRIPTION = "RAISES USER'S ATTACK.")

SING = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = 55,
	POWER_POINTS = 15,
	DESCRIPTION = "PUTS OPPONENT TO SLEEP.")

SKULL_BASH = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 130, 
	ACCURACY = 100,
	POWER_POINTS = 10,
	DESCRIPTION = "RAISES DEFENSE ON FIRST TURN, ATTACKS ON SECOND.")

SKY_ATTACK = Move(
	ELEMENT_TYPE = "FLYING",
	CATEGORY = "PHYSICAL",
	POWER = 140, 
	ACCURACY = 90,
	POWER_POINTS = 5,
	DESCRIPTION = "CHARGES ON FIRST TURN, ATTACKS ON SECOND. MAY CAUSE FLINCHING.")

SLAM = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 80,
	ACCURACY = 75,
	POWER_POINTS = 20,
	DESCRIPTION = None)

SLASH = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 70,
	ACCURACY = 100,
	POWER_POINTS = 20,
	DESCRIPTION = "HIGH CRITICAL HIT RATIO.")

SLEEP_POWDER = Move(
	ELEMENT_TYPE = "GRASS",
	CATEGORY = "STATUS",
	POWER = None, 
	ACCURACY = 75,
	POWER_POINTS = 15,
	DESCRIPTION = "PUTS OPPONENT TO SLEEP.")

SLUDGE = Move(
 	ELEMENT_TYPE = "POISON",
	CATEGORY = "SPECIAL",
	POWER = 65,
	ACCURACY = 100,
	POWER_POINTS = 20,
	DESCRIPTION = "MAY POISON OPPONENT.")

SMOG = Move(
 	ELEMENT_TYPE = "POISON",
	CATEGORY = "SPECIAL",
	POWER = 30,
	ACCURACY = 70,
	POWER_POINTS = 20,
	DESCRIPTION = "MAY POISON OPPONENT.")

SMOKESCREEN = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = 100,
	POWER_POINTS = 20,
	DESCRIPTION = "LOWERS OPPONENT'S ACCURACY.")

SOFT_BOILED = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None, 
	ACCURACY = None,
	POWER_POINTS = 10,
	DESCRIPTION = "USER RECOVERS HALF ITS MAX HP.")

SOLAR_BEAM = Move(
	ELEMENT_TYPE = "GRASS",
	CATEGORY = "SPECIAL",
	POWER = 120, 
	ACCURACY = 100,
	POWER_POINTS = 10,
	DESCRIPTION = "CHARGES ON FIRST TURN, ATTACKS ON SECOND.")

SONIC_BOOM = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "SPECIAL",
	POWER = None,
	ACCURACY = 90,
	POWER_POINTS = 20,
	DESCRIPTION = "ALWAYS INFLICTS 20 HP.")

SPIKE_CANNON = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 20,
	ACCURACY = 100,
	POWER_POINTS = 15,
	DESCRIPTION = "HITS 2-5 TIMES IN ONE TURN.")

SPLASH = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 40,
	DESCRIPTION = "DOESN'T DO ANYTHING.")

SPORE = Move(
 	ELEMENT_TYPE = "GRASS",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = 100,
	POWER_POINTS = 15,
	DESCRIPTION = "PUTS OPPONENT TO SLEEP.")

STOMP = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 65,
	ACCURACY = 100,
	POWER_POINTS = 20,
	DESCRIPTION = "MAY CAUSE FLINCHING.")

STRENGTH = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 80,
	ACCURACY = 100,
	POWER_POINTS = 15,
	DESCRIPTION = None)

STRING_SHOT = Move(
	ELEMENT_TYPE = "BUG",
	CATEGORY = "STATUS",
	POWER = None, 
	ACCURACY = 95,
	POWER_POINTS = 40,
	DESCRIPTION = "SHARPLY LOWERS OPPONENT'S SPEED.")

STRUGGLE = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 50,
	ACCURACY = 100,
	POWER_POINTS = None,
	DESCRIPTION = "ONLY USABLE WHEN ALL PP ARE GONE. HURTS THE USER.")

STUN_SPORE = Move(
	ELEMENT_TYPE = "GRASS",
	CATEGORY = "STATUS",
	POWER = None, 
	ACCURACY = 75,
	POWER_POINTS = 30,
	DESCRIPTION = "PARALYZES OPPONENT.")

SUBMISSION = Move(
 	ELEMENT_TYPE = "FIGHTING",
	CATEGORY = "PHYSICAL",
	POWER = 80,
	ACCURACY = 80,
	POWER_POINTS = 20,
	DESCRIPTION = "USER RECEIVES RECOIL DAMAGE.")

SUBSTITUTE = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 10,
	DESCRIPTION = "USES HP TO CREATES A DECOY THAT TAKES HITS.")

SUPER_FANG = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = None,
	ACCURACY = 90,
	POWER_POINTS = 10,
	DESCRIPTION = "ALWAYS TAKES OFF HALF OF THE OPPONENT'S HP.")

SUPERSONIC = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = 55,
	POWER_POINTS = 20,
	DESCRIPTION = "CONFUSES OPPONENT.")

SURF = Move(
 	ELEMENT_TYPE = "WATER",
	CATEGORY = "SPECIAL",
	POWER = 90,
	ACCURACY = 100,
	POWER_POINTS = 15,
	DESCRIPTION = "HITS ALL ADJACENT POKEMON.")

SWIFT = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "SPECIAL",
	POWER = 60,
	ACCURACY = 100,
	POWER_POINTS = 20,
	DESCRIPTION = "IGNORES ACCURACY AND EVASIVENESS.")

SWORDS_DANCE = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None, 
	ACCURACY = None,
	POWER_POINTS = 20,
	DESCRIPTION = "SHARPLY RAISES USER'S ATTACK.")

TACKLE = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 40,
	ACCURACY = 100,
	POWER_POINTS = 35,
	DESCRIPTION = None)

TAIL_WHIP = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None, 
	ACCURACY = 100,
	POWER_POINTS = 30,
	DESCRIPTION = "LOWERS OPPONENT'S DEFENSE.")

TAKE_DOWN = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 90,
	ACCURACY = 85,
	POWER_POINTS = 20,
	DESCRIPTION = "USER RECEIVES RECOIL DAMAGE.")

TELEPORT = Move(
 	ELEMENT_TYPE = "PSYCHIC",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 20,
	DESCRIPTION = "ALLOWS USER TO FLEE WILD BATTLES; ALSO WARPS PLAYER TO LAST POKECENTER.")

THRASH = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 120,
	ACCURACY = 100,
	POWER_POINTS = 10,
	DESCRIPTION = "USER ATTACKS FOR 2-3 TURNS BUT THEN BECOMES CONFUSED.")

THUNDER = Move(
 	ELEMENT_TYPE = "ELECTRIC",
	CATEGORY = "SPECIAL",
	POWER = 110,
	ACCURACY = 70,
	POWER_POINTS = 10,
	DESCRIPTION = "MAY PARALYZE OPPONENT.")

THUNDER_PUNCH = Move(
	ELEMENT_TYPE = "ELECTRIC",
	CATEGORY = "PHYSICAL",
	POWER = 75,
	ACCURACY = 100,
	POWER_POINTS = 15,
	DESCRIPTION = "MAY PARALYZE OPPONENT.")

THUNDER_SHOCK = Move(
	ELEMENT_TYPE = "ELECTRIC",
	CATEGORY = "SPECIAL",
	POWER = 40, 
	ACCURACY = 100,
	POWER_POINTS = 30,
	DESCRIPTION = "MAY PARALYZE OPPONENT.")

THUNDER_WAVE = Move(
	ELEMENT_TYPE = "ELECTRIC",
	CATEGORY = "STATUS",
	POWER = None, 
	ACCURACY = 90,
	POWER_POINTS = 20,
	DESCRIPTION = "PARALYZES OPPONENT.")

THUNDERBOLT = Move(
 	ELEMENT_TYPE = "ELECTRIC",
	CATEGORY = "SPECIAL",
	POWER = 90,
	ACCURACY = 100,
	POWER_POINTS = 15,
	DESCRIPTION = "MAY PARALYZE OPPONENT.")

TOXIC = Move(
 	ELEMENT_TYPE = "POISON",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = 90,
	POWER_POINTS = 10,
	DESCRIPTION = "BADLY POISONS OPPONENT.")

TRANSFORM = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 10,
	DESCRIPTION = "USER TAKES ON THE FORM AND ATTACKS OF THE OPPONENT.")

TRI_ATTACK = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "SPECIAL",
	POWER = 80, 
	ACCURACY = 100,
	POWER_POINTS = 10,
	DESCRIPTION = "MAY PARALYZE, BURN OR FREEZE OPPONENT.")

TWINEEDLE = Move(
 	ELEMENT_TYPE = "BUG",
	CATEGORY = "PHYSICAL",
	POWER = 25,
	ACCURACY = 100,
	POWER_POINTS = 20,
	DESCRIPTION = "HITS TWICE IN ONE TURN. MAY POISON OPPONENT.")

VICE_GRIP = Move(
	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 55,
	ACCURACY = 100,
	POWER_POINTS = 30,
	DESCRIPTION = None)

VINE_WHIP = Move(
	ELEMENT_TYPE = "GRASS",
	CATEGORY = "PHYSICAL",
	POWER = 45,
	ACCURACY = 100,
	POWER_POINTS = 25,
	DESCRIPTION = None)

WATER_GUN = Move(
	ELEMENT_TYPE = "WATER",
	CATEGORY = "SPECIAL",
	POWER = 40, 
	ACCURACY = 100,
	POWER_POINTS = 25,
	DESCRIPTION = None)

WATERFALL = Move(
 	ELEMENT_TYPE = "WATER",
	CATEGORY = "PHYSICAL",
	POWER = 80,
	ACCURACY = 100,
	POWER_POINTS = 15,
	DESCRIPTION = "MAY CAUSE FLINCHING.")

WHIRLWIND = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 20,
	DESCRIPTION = "IN BATTLES, THE OPPONENT SWITCHES. IN THE WILD, THE POKEMON RUNS.")

WING_ATTACK = Move(
	ELEMENT_TYPE = "FLYING",
	CATEGORY = "PHYSICAL",
	POWER = 60,
	ACCURACY = 100,
	POWER_POINTS = 35,
	DESCRIPTION = None)

WITHDRAW = Move(
 	ELEMENT_TYPE = "WATER",
	CATEGORY = "STATUS",
	POWER = None,
	ACCURACY = None,
	POWER_POINTS = 40,
	DESCRIPTION = "RAISES USER'S DEFENSE.")

WRAP = Move(
 	ELEMENT_TYPE = "NORMAL",
	CATEGORY = "PHYSICAL",
	POWER = 15,
	ACCURACY = 90,
	POWER_POINTS = 20,
	DESCRIPTION = "TRAPS OPPONENT, DAMAGING THEM FOR 4-5 TURNS.")

"""MOVEionary containing this generations Pokemon moves.

Key value contains corresponding MOVEionary containing the attributes for the move property.
"""

MOVES = dict(
	ABSORB = ABSORB,
	ACID = ACID,
	ACID_ARMOUR = ACID_ARMOUR,
	AGILITY = AGILITY,
	AMNESIA = AMNESIA,
	AURORA_BEAM = AURORA_BEAM,
	BARRAGE = BARRAGE,
	BARRIER = BARRIER,
	BIDE = BIDE,
	BIND = BIND,
	BITE = BITE,
	BLIZZARD = BLIZZARD,
	BODY_SLAM = BODY_SLAM,
	BONEMERANG = BONEMERANG,
	BONE_CLUB = BONE_CLUB,
	BUBBLE = BUBBLE,
	BUBBLE_BEAM = BUBBLE_BEAM,
	CLAMP = CLAMP,
	COMET_PUNCH = COMET_PUNCH,
	CONFUSE_RAY = CONFUSE_RAY,
	CONFUSION = CONFUSION,
	CONSTRICT = CONSTRICT,
	CONVERSION = CONVERSION,
	COUNTER = COUNTER,
	CRABHAMMER = CRABHAMMER,
	CUT = CUT,
	DEFENSE_CURL = DEFENSE_CURL,
	DIG = DIG,
	DISABLE = DISABLE,
	DIZZY_PUNCH = DIZZY_PUNCH,
	DOUBLE_EDGE = DOUBLE_EDGE,
	DOUBLE_KICK = DOUBLE_KICK,
	DOUBLE_SLAP = DOUBLE_SLAP,
	DOUBLE_TEAM = DOUBLE_TEAM,
	DRAGON_RAGE = DRAGON_RAGE,
	DREAM_EATER = DREAM_EATER,
	DRILL_PECK = DRILL_PECK,
	EARTHQUAKE = EARTHQUAKE,
	EGG_BOMB = EGG_BOMB,
	EMBER = EMBER,
	EXPLOSION = EXPLOSION,
	FIRE_BLAST = FIRE_BLAST,
	FIRE_PUNCH = FIRE_PUNCH,
	FIRE_SPIN = FIRE_SPIN,
	FISSURE = FISSURE,
	FLAMETHROWER = FLAMETHROWER,
	FLASH = FLASH,
	FLY = FLY,
	FOCUS_ENERGY = FOCUS_ENERGY,
	FURY_ATTACK = FURY_ATTACK,
	FURY_SWIPES = FURY_SWIPES,
	GLARE = GLARE,
	GROWL = GROWL,
	GROWTH = GROWTH,
	GUILLOTINE = GUILLOTINE,
	GUST = GUST,
	HARDEN = HARDEN,
	HAZE = HAZE,
	HEADBUTT = HEADBUTT,
	HORN_ATTACK = HORN_ATTACK,
	HORN_DRILL = HORN_DRILL,
	HYDRO_PUMP = HYDRO_PUMP,
	HYPER_BEAM = HYPER_BEAM,
	HYPER_FANG = HYPER_FANG,
	HYPNOSIS = HYPNOSIS,
	ICE_BEAM = ICE_BEAM,
	ICE_PUNCH = ICE_PUNCH,
	JUMP_KICK = JUMP_KICK,
	KARATE_CHOP = KARATE_CHOP,
	KINESIS = KINESIS,
	LEECH_LIFE = LEECH_LIFE,
	LEECH_SEED = LEECH_SEED,
	LEER = LEER,
	LICK = LICK,
	LIGHT_SCREEN = LIGHT_SCREEN,
	LOVELY_KISS = LOVELY_KISS,
	LOW_KICK = LOW_KICK,
	MEDITATE = MEDITATE,
	MEGA_DRAIN = MEGA_DRAIN,
	MEGA_KICK = MEGA_KICK,
	MEGA_PUNCH = MEGA_PUNCH,
	METRONOME = METRONOME,
	MIMIC = MIMIC,
	MINIMIZE = MINIMIZE,
	MIRROR_MOVE = MIRROR_MOVE,
	MIST = MIST,
	NIGHT_SHADE = NIGHT_SHADE,
	PAY_DAY = PAY_DAY,
	PECK = PECK,
	PETAL_DANCE = PETAL_DANCE,
	PIN_MISSILE = PIN_MISSILE,
	POISON_GAS = POISON_GAS,
	POISON_POWDER = POISON_POWDER,
	POISON_STING = POISON_STING,
	POUND = POUND,
	PSYBEAM = PSYBEAM,
	PSYCHIC = PSYCHIC,
	PSYWAVE = PSYWAVE,
	QUICK_ATTACK = QUICK_ATTACK,
	RAGE = RAGE,
	RAZOR_LEAF = RAZOR_LEAF,
	RAZOR_WIND = RAZOR_WIND,
	RECOVER = RECOVER,
	REFLECT = REFLECT,
	REST = REST,
	ROAR = ROAR,
	ROCK_SLIDE = ROCK_SLIDE,
	ROCK_THROW = ROCK_THROW,
	ROLLING_KICK = ROLLING_KICK,
	SAND_ATTACK = SAND_ATTACK,
	SCRATCH = SCRATCH,
	SCREECH = SCREECH,
	SEISMIC_TOSS = SEISMIC_TOSS,
	SELF_DESTRUCT = SELF_DESTRUCT,
	SHARPEN = SHARPEN,
	SING = SING,
	SKULL_BASH = SKULL_BASH,
	SKY_ATTACK = SKY_ATTACK,
	SLAM = SLAM,
	SLASH = SLASH,
	SLEEP_POWDER = SLEEP_POWDER,
	SLUDGE = SLUDGE,
	SMOG = SMOG,
	SMOKESCREEN = SMOKESCREEN,
	SOFT_BOILED = SOFT_BOILED,
	SOLAR_BEAM = SOLAR_BEAM,
	SONIC_BOOM = SONIC_BOOM,
	SPIKE_CANNON = SPIKE_CANNON,
	SPLASH = SPLASH,
	SPORE = SPORE,
	STOMP = STOMP,
	STRENGTH = STRENGTH,
	STRING_SHOT = STRING_SHOT,
	STRUGGLE = STRUGGLE,
	STUN_SPORE = STUN_SPORE,
	SUBMISSION = SUBMISSION,
	SUBSTITUTE = SUBSTITUTE,
	SUPERSONIC = SUPERSONIC,
	SUPER_FANG = SUPER_FANG,
	SURF = SURF,
	SWIFT = SWIFT,
	SWORDS_DANCE = SWORDS_DANCE,
	TACKLE = TACKLE,
	TAIL_WHIP = TAIL_WHIP,
	TAKE_DOWN = TAKE_DOWN,
	TELEPORT = TELEPORT,
	THRASH = THRASH,
	THUNDER = THUNDER,
	THUNDERBOLT = THUNDERBOLT,
	THUNDER_PUNCH = THUNDER_PUNCH,
	THUNDER_SHOCK = THUNDER_SHOCK,
	THUNDER_WAVE = THUNDER_WAVE,
	TOXIC = TOXIC,
	TRANSFORM = TRANSFORM,
	TRI_ATTACK = TRI_ATTACK,
	TWINEEDLE = TWINEEDLE,
	VICE_GRIP = VICE_GRIP,
	VINE_WHIP = VINE_WHIP,
	WATERFALL = WATERFALL,
	WATER_GUN = WATER_GUN,
	WHIRLWIND = WHIRLWIND,
	WING_ATTACK = WING_ATTACK,
	WITHDRAW = WITHDRAW) 

"""Tuple containing the names for the different Pokemon moves.

Sequence entries are generated from the moves MOVEionary. 
Requires Pokemon move be entered within moves colleciton.
"""

NAMES = tuple(dict.keys(MOVES))
